# Generated by Django 3.1.3 on 2020-11-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteName', models.CharField(max_length=100)),
                ('cellIds', models.TextField()),
                ('siteAddress', models.TextField()),
                ('location', models.TextField()),
                ('siteFiles', models.FileField(upload_to='')),
                ('siteConditions', models.TextField()),
                ('siteBriaf', models.TextField()),
                ('siteState', models.TextField()),
                ('siteOwner', models.TextField()),
                ('sitecity', models.TextField()),
                ('siteProvider', models.TextField()),
                ('sitFiberNode', models.TextField()),
            ],
        ),
    ]
